Update jitpack.yml
elimu-ai/analytics pull request #142
Opened 2023-12-04 03:07 UTC by jpascoe32fb

This PR is for the Add jitpack.yml issue

2023-12-04 05:56 UTC, jo-elimu requested changes
Will we have to remove Java 11 from https://github.com/elimu-ai/analytics/blob/main/.github/workflows/gradle.yml as well?

2023-12-05 01:07 UTC, jpascoe32fb commented
> Will we have to remove Java 11 from https://github.com/elimu-ai/analytics/blob/main/.github/workflows/gradle.yml as well?

After looking into it, I don't think that is necessary. The 11 and 17 in that file simply makes it so that it tests against both Java 11 and 17. The matrix.java variable dynamically sets the java version for each run so I don't necessarily think it is necessary but I am willing to do it if you think it should be done.

2023-12-05 13:12 UTC, nya-elimu approved these changes

2023-12-06 09:10 UTC, jo-elimu approved these changes
@jpascoe32fb This change looks perfect to me. Please merge 🙂

2023-12-06 22:01 UTC, merged